spring.application.name=lucene-demo
spring.config.import=classpath:secrets-dev.properties
#spring.config.import=optional:file:secrets-dev.properties

#server.address=0.0.0.0
server.forward-headers-strategy=framework

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

spring.cache.type=caffeine
#spring.cache.type=redis
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
##spring.data.redis.password=
#spring.data.redis.timeout=6000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rkthakur.1104@gmail.com
spring.mail.password=${email.pass}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.debug=false
spring.mail.properties.mail.smtp.debug=false

#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/skyhub-realm
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9090/realms/skyhub-realm/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://auth.jamuarasoft.com/realms/skyhub-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://auth.jamuarasoft.com/realms/skyhub-realm/protocol/openid-connect/certs

app.keycloak.admin.clientId=admin-client
#app.keycloak.admin.clientSecret=X2l1qaO5fqCnePDUMcEJ452LHiqV8ZaX
app.keycloak.admin.clientSecret=gHw7JlCIuCvQu8n72EdCzmD60GYa9Ktu
#bP624bhjuuLQ2tflW5k2nHw1JoiuRbkh
#PeRdHQyvy5UXsZDpYOAE3Oi1rJ8a9E2V
#app.keycloak.realm=skyhub-realm
app.keycloak.serverUrl=https://auth.jamuarasoft.com
app.keycloak.realm=skyhub-realm
#app.keycloak.serverUrl=http://localhost:9090

tbo.client.username=Sardarji
tbo.client.password=Sardarji@1234

payu.merchant.key=${payu.key}
payu.merchant.salt=${payu.salt}

spring.profiles.active=dev

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG